<#
.SYNOPSIS
    Metrics collection script — reads changelog data and generates process improvement reports.
    
    Usage: .opencode\metrics\collect.ps1 [-Days 7] [-ReportPath "reports/metrics-report.md"]
    
    This is the core of the data feedback loop:
    
    Collect Data → Compute Metrics → Generate Report → Identify Bottlenecks → Improve Process
         ↑                                                                │
         └─────────────────── Apply Improvement ──────────────────────────┘

.PARAMETER Days
    Number of days to look back. Default: 7

.PARAMETER ReportPath
    Where to write the report. Default: .opencode\metrics\latest-report.md

.EXAMPLE
    .opencode\metrics\collect.ps1 -Days 7 -ReportPath "reports/sprint-12.md"
#>

param(
    [int]$Days = 7,
    [string]$ReportPath = ""
)

$ProjectPath = (Get-Item $PSScriptRoot).Parent.Parent.FullName
$changelogDir = Join-Path $ProjectPath ".opencode\changelog"

if (-not $ReportPath) {
    $ReportPath = Join-Path $PSScriptRoot "latest-report.md"
}

# Ensure report directory exists
$reportDir = Split-Path $ReportPath -Parent
if (-not (Test-Path $reportDir)) {
    New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
}

Write-Host "=== Data Feedback Loop: Collecting Metrics ===" -ForegroundColor Cyan
Write-Host "Looking back: $Days days"
Write-Host "Changelog dir: $changelogDir"
Write-Host "Report: $ReportPath"

# Collect all changelog entries from the last N days
$cutoff = (Get-Date).AddDays(-$Days)
$allRecords = @()

if (Test-Path $changelogDir) {
    $logFiles = Get-ChildItem -Path $changelogDir -Filter "*.jsonl" | Where-Object {
        $_.LastWriteTime -ge $cutoff
    }
    
    foreach ($file in $logFiles) {
        Get-Content $file -Encoding UTF8 | ForEach-Object {
            try {
                $allRecords += $_ | ConvertFrom-Json
            } catch {
                # Skip malformed lines
            }
        }
    }
}

Write-Host "Found $($allRecords.Count) records in changelog" -ForegroundColor Yellow

# Compute metrics
$totalTasks = ($allRecords | Where-Object { $_.status -eq "started" }).Count
$completedTasks = ($allRecords | Where-Object { $_.status -eq "completed" -or $_.status -eq "passed" }).Count
$failedTasks = ($allRecords | Where-Object { $_.status -eq "failed" -or $_.status -eq "rejected" }).Count

# First-pass rate: tasks that passed on first try
$firstPass = ($allRecords | Where-Object { $_.status -eq "passed" -and $_.action -ne "review" }).Count
$firstPassRate = if ($totalTasks -gt 0) { [math]::Round($firstPass / $totalTasks * 100, 1) } else { 0 }

# Common failure modes
$failureReasons = @{}
$allRecords | Where-Object { $_.status -eq "failed" -or $_.status -eq "rejected" } | ForEach-Object {
    $key = $_.action
    if ($failureReasons.ContainsKey($key)) {
        $failureReasons[$key] += 1
    } else {
        $failureReasons[$key] = 1
    }
}

# Average attempts per task
$taskAttempts = @{}
$allRecords | ForEach-Object {
    $key = $_.task
    if ($key) {
        if (-not $taskAttempts.ContainsKey($key)) { $taskAttempts[$key] = @() }
        $taskAttempts[$key] += $_
    }
}
$avgAttempts = 0
if ($taskAttempts.Count -gt 0) {
    $avgAttempts = [math]::Round(($taskAttempts.Values | ForEach-Object { $_.Count } | Measure-Object -Average).Average, 1)
}

# Files changed count
$filesChanged = @{}
$allRecords | ForEach-Object {
    if ($_.files) {
        foreach ($f in $_.files) {
            if ($filesChanged.ContainsKey($f)) { $filesChanged[$f] += 1 }
            else { $filesChanged[$f] = 1 }
        }
    }
}
$topFiles = $filesChanged.GetEnumerator() | Sort-Object Value -Descending | Select-Object -First 5

# Agent activity
$agentActivity = @{}
$allRecords | ForEach-Object {
    $agent = $_.agent
    if ($agent) {
        if ($agentActivity.ContainsKey($agent)) { $agentActivity[$agent] += 1 }
        else { $agentActivity[$agent] = 1 }
    }
}

# Generate report
$reportContent = @"
# Metrics Report — $(Get-Date -Format "yyyy-MM-dd HH:mm")

Generated by .opencode\metrics\collect.ps1 | Period: $($cutoff.ToString("yyyy-MM-dd")) to $(Get-Date -Format "yyyy-MM-dd")

---

## Summary

| Metric | Value |
|--------|-------|
| Total tasks | $totalTasks |
| Completed | $completedTasks |
| Failed | $failedTasks |
| First-pass rate | $firstPassRate% |
| Avg attempts per task | $avgAttempts |
| Total changelog records | $($allRecords.Count) |

---

## Failure Analysis

### By action type

"@

if ($failureReasons.Count -gt 0) {
    $reportContent += "| Action | Failures |`n|--------|----------|`n"
    $failureReasons.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object {
        $reportContent += "| $($_.Key) | $($_.Value) |`n"
    }
} else {
    $reportContent += "No failures recorded in this period.`n"
}

$reportContent += @"

### Top 5 most modified files

| File | Changes |
|------|---------|
"@

foreach ($f in $topFiles) {
    $reportContent += "| $($f.Key) | $($f.Value) |`n"
}

$reportContent += @"

---

## Agent Activity

| Agent | Operations |
|-------|-----------|
"@

$agentActivity.GetEnumerator() | Sort-Object Value -Descending | ForEach-Object {
    $reportContent += "| $($_.Key) | $($_.Value) |`n"
}

$reportContent += @"

---

## Process Improvement Recommendations

### Based on this period's data:

"@

if ($firstPassRate -lt 50) {
    $reportContent += @"
- 🔴 **Low first-pass rate ($firstPassRate%)**: More than half of tasks need rework.
  - Check if task breakdown is too coarse
  - Review prompt templates for missing constraints
  - Consider splitting large tasks into smaller ones

"@
} elseif ($firstPassRate -lt 80) {
    $reportContent += @"
- 🟡 **Moderate first-pass rate ($firstPassRate%)**: Some tasks need rework.
  - Review recent failure patterns for common issues
  - Consider adding more examples to prompt templates

"@
} else {
    $reportContent += @"
- 🟢 **Good first-pass rate ($firstPassRate%)**: Most tasks pass on first try. Keep it up.

"@
}

if ($avgAttempts -gt 3) {
    $reportContent += @"
- 🟡 **High revision count ($avgAttempts attempts/task)**: Tasks are going through too many iterations.
  - Check if acceptance criteria are clear enough
  - Consider adding more constraints to task specs

"@
}

$reportContent += @"
### Actions for next sprint:

- [ ] Review top failure modes and fix root causes
- [ ] Update prompt templates based on findings
- [ ] Share report with team

---

*Report auto-generated by collect.ps1. Run again with .opencode\metrics\collect.ps1*
"@

# Write report
Set-Content -Path $ReportPath -Value $reportContent -Encoding UTF8

Write-Host "`n=== Report generated ===" -ForegroundColor Green
Write-Host "Report: $ReportPath"
Write-Host "`nKey metrics:" -ForegroundColor Cyan
Write-Host "  First-pass rate: $firstPassRate%"
Write-Host "  Avg attempts/task: $avgAttempts"
Write-Host "  Failures: $failedTasks"
Write-Host "`nTop improvement priority:" -ForegroundColor Yellow
if ($firstPassRate -lt 50) {
    Write-Host "  → Improve first-pass rate (split tasks, refine prompts)" -ForegroundColor Red
} elseif ($avgAttempts -gt 3) {
    Write-Host "  → Reduce revision count (clearer acceptance criteria)" -ForegroundColor Yellow
} else {
    Write-Host "  → Process is healthy. Maintain current practices." -ForegroundColor Green
}

exit 0
